# Generated by Django 4.0.5 on 2022-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_no', models.TextField(max_length=50)),
                ('first_name', models.TextField(max_length=25)),
                ('last_name', models.TextField(max_length=25)),
                ('dob', models.DateField()),
            ],
        ),
    ]
