# Generated by Django 4.0.5 on 2022-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='identification_no',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
